const { Client } = require('pg');

// Read the connection string from the environment.
// NEVER commit database credentials to the repository.
// Set it locally, e.g. (PowerShell):
//   $env:DATABASE_URL="postgresql://postgres.<ref>:<password>@aws-1-eu-north-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
//   node setup-db.js
const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
  console.error('Missing DATABASE_URL environment variable.');
  console.error('Set it first (see the comment at the top of setup-db.js), then run: node setup-db.js');
  process.exit(1);
}

const sql = `
-- 1. User Profiles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  student_id TEXT,
  university TEXT DEFAULT 'Campus University',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 2. Mood Tracking History
CREATE TABLE IF NOT EXISTS public.mood_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  mood TEXT NOT NULL,
  factors TEXT[] DEFAULT '{}',
  notes TEXT,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 3. Therapy Exercise Progress
CREATE TABLE IF NOT EXISTS public.therapy_progress (
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  exercise_id TEXT NOT NULL,
  completed_steps INTEGER[] DEFAULT '{}',
  notes TEXT,
  completion_date TIMESTAMP WITH TIME ZONE,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT now(),
  PRIMARY KEY (user_id, exercise_id)
);

-- 4. Group Chat Messages
CREATE TABLE IF NOT EXISTS public.group_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id TEXT NOT NULL,
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'user', -- 'user', 'system', 'voice'
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 5. User Group Movements (Analytics)
CREATE TABLE IF NOT EXISTS public.user_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  from_mood TEXT,
  to_mood TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 6. Appointments
CREATE TABLE IF NOT EXISTS public.appointments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  counselor_id TEXT NOT NULL,
  counselor_name TEXT NOT NULL,
  appointment_date DATE NOT NULL,
  appointment_time TIME NOT NULL,
  status TEXT DEFAULT 'scheduled', -- 'scheduled', 'cancelled', 'completed'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 7. Meditation Sessions
CREATE TABLE IF NOT EXISTS public.meditation_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  type TEXT NOT NULL,
  duration INTEGER NOT NULL, -- in minutes
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 8. Meditation Goals
CREATE TABLE IF NOT EXISTS public.meditation_goals (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  goal_text TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT false,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- 9. Support Tickets
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE SET NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable Row Level Security (RLS)
DO $$ 
BEGIN
  ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.mood_entries ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.therapy_progress ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.group_messages ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.user_movements ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.meditation_sessions ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.meditation_goals ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
EXCEPTION
  WHEN others THEN NULL;
END $$;

-- Create Policies
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own profile') THEN
    CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can update own profile') THEN
    CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can handle own mood') THEN
    CREATE POLICY "Users can handle own mood" ON public.mood_entries FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can handle own therapy') THEN
    CREATE POLICY "Users can handle own therapy" ON public.therapy_progress FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Anyone can view group messages') THEN
    CREATE POLICY "Anyone can view group messages" ON public.group_messages FOR SELECT USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated users can post messages') THEN
    CREATE POLICY "Authenticated users can post messages" ON public.group_messages FOR INSERT WITH CHECK (auth.role() = 'authenticated');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can view own movements') THEN
    CREATE POLICY "Users can view own movements" ON public.user_movements FOR SELECT USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can handle own appointments') THEN
    CREATE POLICY "Users can handle own appointments" ON public.appointments FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can handle own meditation sessions') THEN
    CREATE POLICY "Users can handle own meditation sessions" ON public.meditation_sessions FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can handle own meditation goals') THEN
    CREATE POLICY "Users can handle own meditation goals" ON public.meditation_goals FOR ALL USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can handle own support tickets') THEN
    CREATE POLICY "Users can handle own support tickets" ON public.support_tickets FOR ALL USING (auth.uid() = user_id OR email = (SELECT email FROM auth.users WHERE id = auth.uid()));
  END IF;
END $$;
`;

async function run() {
  const client = new Client({
    connectionString: DATABASE_URL,
    ssl: {
      rejectUnauthorized: false
    }
  });

  try {
    await client.connect();
    console.log('Connected to Supabase Database');
    await client.query(sql);
    
    // Grant permissions to the authenticated role for Supabase
    await client.query(`
      GRANT USAGE ON SCHEMA public TO authenticated;
      GRANT USAGE ON SCHEMA public TO anon;
      GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
      GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
    `);

    console.log('Schema created and permissions granted successfully');
  } catch (err) {
    console.error('Error executing SQL:', err);
  } finally {
    await client.end();
  }
}

run();
