import {
  FaAnchor,
  FaArrowDown,
  FaArrowRight,
  FaBalanceScale,
  FaBars,
  FaBed,
  FaBolt,
  FaBook,
  FaBookOpen,
  FaBookmark,
  FaBrain,
  FaBullseye,
  FaCalculator,
  FaCalendar,
  FaCalendarCheck,
  FaCalendarPlus,
  FaCalendarTimes,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckCircle,
  FaCheckDouble,
  FaChevronRight,
  FaCircle,
  FaCircleNotch,
  FaClipboardList,
  FaClock,
  FaCloudRain,
  FaCoffee,
  FaCog,
  FaCogs,
  FaComment,
  FaComments,
  FaCompass,
  FaCompress,
  FaDice,
  FaDownload,
  FaEdit,
  FaExchangeAlt,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExternalLinkAlt,
  FaEye,
  FaFeatherAlt,
  FaFilePdf,
  FaFire,
  FaFlag,
  FaFrown,
  FaGamepad,
  FaHandHoldingHeart,
  FaHandsHelping,
  FaHandshake,
  FaHeadphones,
  FaHeart,
  FaHeartbeat,
  FaHistory,
  FaInbox,
  FaInfoCircle,
  FaLayerGroup,
  FaLeaf,
  FaLifeRing,
  FaLightbulb,
  FaList,
  FaLock,
  FaLungs,
  FaMagic,
  FaMapMarkerAlt,
  FaSpa,
  FaMicrophone,
  FaMobileAlt,
  FaMoon,
  FaMusic,
  FaNewspaper,
  FaOm,
  FaPaintBrush,
  FaPalette,
  FaPaperPlane,
  FaPause,
  FaPhone,
  FaPhoneAlt,
  FaPlay,
  FaPlus,
  FaPlusCircle,
  FaPoll,
  FaProjectDiagram,
  FaPuzzlePiece,
  FaQuestion,
  FaQuestionCircle,
  FaRandom,
  FaRedo,
  FaSync,
  FaRobot,
  FaRocket,
  FaRunning,
  FaSave,
  FaShieldAlt,
  FaSignInAlt,
  FaSignOutAlt,
  FaSignal,
  FaSmile,
  FaSort,
  FaStar,
  FaStepBackward,
  FaStepForward,
  FaStop,
  FaStopwatch,
  FaSun,
  FaSyncAlt,
  FaTasks,
  FaTimes,
  FaTimesCircle,
  FaToggleOn,
  FaToolbox,
  FaTools,
  FaTrash,
  FaTree,
  FaTrophy,
  FaUndo,
  FaUser,
  FaUserCircle,
  FaUserFriends,
  FaUserGraduate,
  FaUserMd,
  FaUserPlus,
  FaUserShield,
  FaUserTimes,
  FaUsers,
  FaUsersCog,
  FaVideo,
  FaVolumeDown,
  FaVolumeUp,
  FaVoteYea,
  FaWalking,
  FaWater,
  FaWind,
  FaSadTear,
  FaMeh,
  FaLaugh,
  FaRainbow,
  FaPencilAlt,
  FaEraser,
  FaGraduationCap,
  FaLaptopCode,
  FaFlask,
  FaBriefcase,
  FaTheaterMasks,
  FaChalkboardTeacher,
  FaDrum,
  FaDumbbell,
  FaCloud,
  FaArrowUp,
  FaBell,
  FaAdjust,
  FaGlobe,
  FaDatabase,
  FaTrashAlt,
  FaHome,
  FaAmbulance,
  FaEnvelope,
  FaPlayCircle,
  FaArrowLeft,
  FaCommentDots,
} from 'react-icons/fa'

const ICONS = {
  "anchor": FaAnchor,
  "arrow-down": FaArrowDown,
  "arrow-right": FaArrowRight,
  "balance-scale": FaBalanceScale,
  "bars": FaBars,
  "bed": FaBed,
  "bolt": FaBolt,
  "book": FaBook,
  "book-open": FaBookOpen,
  "bookmark": FaBookmark,
  "brain": FaBrain,
  "bullseye": FaBullseye,
  "calculator": FaCalculator,
  "calendar": FaCalendar,
  "calendar-check": FaCalendarCheck,
  "calendar-plus": FaCalendarPlus,
  "calendar-times": FaCalendarTimes,
  "chart-bar": FaChartBar,
  "chart-line": FaChartLine,
  "chart-pie": FaChartPie,
  "check": FaCheck,
  "check-circle": FaCheckCircle,
  "check-double": FaCheckDouble,
  "chevron-right": FaChevronRight,
  "circle": FaCircle,
  "circle-notch": FaCircleNotch,
  "clipboard-list": FaClipboardList,
  "clock": FaClock,
  "cloud-rain": FaCloudRain,
  "coffee": FaCoffee,
  "cog": FaCog,
  "cogs": FaCogs,
  "comment": FaComment,
  "comments": FaComments,
  "compass": FaCompass,
  "compress": FaCompress,
  "dice": FaDice,
  "download": FaDownload,
  "edit": FaEdit,
  "exchange-alt": FaExchangeAlt,
  "exclamation-circle": FaExclamationCircle,
  "exclamation-triangle": FaExclamationTriangle,
  "external-link-alt": FaExternalLinkAlt,
  "eye": FaEye,
  "feather-alt": FaFeatherAlt,
  "file-pdf": FaFilePdf,
  "fire": FaFire,
  "flag": FaFlag,
  "frown": FaFrown,
  "gamepad": FaGamepad,
  "hand-holding-heart": FaHandHoldingHeart,
  "hands-helping": FaHandsHelping,
  "handshake": FaHandshake,
  "headphones": FaHeadphones,
  "heart": FaHeart,
  "heartbeat": FaHeartbeat,
  "history": FaHistory,
  "inbox": FaInbox,
  "info-circle": FaInfoCircle,
  "layer-group": FaLayerGroup,
  "leaf": FaLeaf,
  "life-ring": FaLifeRing,
  "lightbulb": FaLightbulb,
  "list": FaList,
  "list-check": FaClipboardList,
  "lock": FaLock,
  "lungs": FaLungs,
  "magic": FaMagic,
  "map-marker-alt": FaMapMarkerAlt,
  "meditation": FaSpa,
  "microphone": FaMicrophone,
  "mobile-alt": FaMobileAlt,
  "moon": FaMoon,
  "music": FaMusic,
  "newspaper": FaNewspaper,
  "om": FaOm,
  "paint-brush": FaPaintBrush,
  "palette": FaPalette,
  "paper-plane": FaPaperPlane,
  "pause": FaPause,
  "phone": FaPhone,
  "phone-alt": FaPhoneAlt,
  "play": FaPlay,
  "plus": FaPlus,
  "plus-circle": FaPlusCircle,
  "poll": FaPoll,
  "project-diagram": FaProjectDiagram,
  "puzzle-piece": FaPuzzlePiece,
  "question": FaQuestion,
  "question-circle": FaQuestionCircle,
  "random": FaRandom,
  "redo": FaRedo,
  "refresh": FaSync,
  "repeat": FaRedo,
  "robot": FaRobot,
  "rocket": FaRocket,
  "running": FaRunning,
  "save": FaSave,
  "shield-alt": FaShieldAlt,
  "sign-in-alt": FaSignInAlt,
  "sign-out-alt": FaSignOutAlt,
  "signal": FaSignal,
  "smile": FaSmile,
  "sort": FaSort,
  "spa": FaSpa,
  "star": FaStar,
  "step-backward": FaStepBackward,
  "step-forward": FaStepForward,
  "stop": FaStop,
  "stopwatch": FaStopwatch,
  "sun": FaSun,
  "sync": FaSync,
  "sync-alt": FaSyncAlt,
  "tasks": FaTasks,
  "times": FaTimes,
  "times-circle": FaTimesCircle,
  "toggle-on": FaToggleOn,
  "toolbox": FaToolbox,
  "tools": FaTools,
  "trash": FaTrash,
  "tree": FaTree,
  "trophy": FaTrophy,
  "undo": FaUndo,
  "user": FaUser,
  "user-circle": FaUserCircle,
  "user-friends": FaUserFriends,
  "user-graduate": FaUserGraduate,
  "user-md": FaUserMd,
  "user-plus": FaUserPlus,
  "user-shield": FaUserShield,
  "user-times": FaUserTimes,
  "users": FaUsers,
  "users-cog": FaUsersCog,
  "video": FaVideo,
  "volume-down": FaVolumeDown,
  "volume-up": FaVolumeUp,
  "vote-yea": FaVoteYea,
  "walking": FaWalking,
  "water": FaWater,
  "wind": FaWind,
  "zap": FaBolt,
  "sad-tear": FaSadTear,
  "meh": FaMeh,
  "laugh": FaLaugh,
  "rainbow": FaRainbow,
  "pencil-alt": FaPencilAlt,
  "eraser": FaEraser,
  "graduation-cap": FaGraduationCap,
  "laptop-code": FaLaptopCode,
  "flask": FaFlask,
  "briefcase": FaBriefcase,
  "theater-masks": FaTheaterMasks,
  "chalkboard-teacher": FaChalkboardTeacher,
  "drum": FaDrum,
  "dumbbell": FaDumbbell,
  "cloud": FaCloud,
  "arrow-up": FaArrowUp,
  "bell": FaBell,
  "adjust": FaAdjust,
  "globe": FaGlobe,
  "database": FaDatabase,
  "trash-alt": FaTrashAlt,
  "home": FaHome,
  "ambulance": FaAmbulance,
  "envelope": FaEnvelope,
  "play-circle": FaPlayCircle,
  "arrow-left": FaArrowLeft,
  "comment-dots": FaCommentDots,
}

export default function Icon({ icon, spin = false, className = '', ...props }) {
  const key = String(icon || '')
    .trim()
    .replace(/^fa[sd]r?\s+/, '')
    .replace(/^fa-/, '')
  const Cmp = ICONS[key]
  if (!Cmp) return <span className={className}>{icon}</span>
  const cls = [spin ? 'animate-spin' : '', className].filter(Boolean).join(' ').trim()
  return <Cmp className={cls} {...props} />
}
