import { createContext, useContext, useEffect, useState } from 'react'

const translations = {
  en: {
    // Landing
    welcome_title: 'Campus Mindspace',
    welcome_subtitle: 'Your personal sanctuary for mental wellness',
    welcome_description:
      'A comprehensive mental health and wellness platform designed specifically for university students. Find support, resources, and tools to navigate the challenges of academic life.',
    enter_title: 'Ready to begin?',
    enter_description:
      'Enter the dashboard to explore mood tracking, meditation, therapy tools, games and peer support groups.',
    enter_btn: 'Enter Dashboard',
    secure_trusted: 'Secure & Trusted',
    professional_counselors: 'Professional Counselors',
    privacy_protected: 'Privacy Protected',

    // Navigation
    nav_home: 'Home',
    nav_therapy: 'Therapy',
    nav_meditation: 'Meditation',
    nav_resources: 'Resources',
    nav_appointments: 'Appointments',
    nav_games: 'Mind Games',
    nav_groups: 'Group Chat',
    nav_insights: 'Insights',
    admin_shortcut: 'Admin',
    profile_settings: 'Settings',
    profile_help: 'Help & Support',
    exit_home: 'Exit to Home',

    // Home
    welcome_back: 'Welcome back, {name}!',
    stat_streak: 'Day Streak',
    stat_wellness: 'Wellness Score',
    stat_sessions: 'Sessions',
    daily_tip_badge: 'Daily Tip',
    daily_tip_title: 'Wellness Insight',
    new_tip: 'New Tip',
    save_tip: 'Save',
    tip_saved: 'Tip saved to your collection',
    quick_actions: 'Quick Actions',
    quick_actions_subtitle: 'Access your wellness tools and resources',
    therapy_title: 'Therapy Resources',
    therapy_description: 'Access CBT, DBT, and mindfulness exercises',
    meditation_title: 'Meditation',
    meditation_description: 'Guided sessions for stress relief and focus',
    resources_title: 'Resources',
    resources_description: 'Music, videos, and study aids',
    appointment_title: 'Book Session',
    appointment_description: 'Schedule time with a counselor',
    games_title: 'Mind Games',
    games_description: 'Fun activities to boost your mood',
    games_tab_cognitive: 'Cognitive Games',
    games_tab_wellness: 'Wellness Activities',
    games_tab_creativity: 'Creative Tools',
    games_tab_social: 'Social Games',
    groups_title: 'Group Chat',
    groups_description: 'Connect with others feeling the same way',
    complete_pct: '{p}% Complete',
    sessions_count: '3 Sessions',
    members_count: '5 Members',
    popular: 'Popular',
    new_badge: 'New',
    recent_activity: 'Recent Activity',
    live: 'Live',
    activity_meditation_title: 'Meditation Session Completed',
    activity_meditation_desc: '5-minute breathing exercise • 2 minutes ago',
    activity_mood_title: 'Mood Check-in',
    activity_mood_desc: 'Feeling positive today • 15 minutes ago',
    activity_therapy_title: 'Therapy Exercise',
    activity_therapy_desc: 'CBT worksheet completed • 1 hour ago',
    pts: '+{n} pts',
    your_achievements: 'Your Achievements',
    achievements_subtitle: 'Celebrate your wellness milestones',
    badge_streak: 'Streak Master',
    badge_streak_desc: '7-day wellness streak',
    badge_zen: 'Zen Seeker',
    badge_zen_desc: '10 meditation sessions',
    badge_champion: 'Wellness Champion',
    badge_champion_desc: 'Complete 30 activities',
    badge_helper: 'Community Helper',
    badge_helper_desc: 'Help 5 peers',
    mood_tracker_title: 'How are you feeling today?',
    update_mood: 'Update Mood',
    view_history: 'View History',
    analytics: 'Analytics',
    mood_overwhelmed: 'Feeling overwhelmed',
    mood_sleep: 'Having sleep issues',
    mood_social: 'Stressed socially',
    mood_happy: 'Feeling great!',
    mood_anxious: 'Feeling anxious',
    mood_lonely: 'Feeling lonely',
    mood_updated: 'Mood updated successfully!',
    coming_soon: 'Coming Soon',
    coming_soon_desc:
      'This section is being rebuilt in React. In the meantime you can explore it in the original prototype at http://127.0.0.1:8000/dashboard.html',

    // Chatbot
    chatbot_title: "Hi there, I'm MindBot!",
    chatbot_subtitle: 'Your mental wellness companion',
    chatbot_placeholder: 'Type your message...',

    // System status
    status_checking: 'Checking System...',
    status_cloud: 'Cloud Connected',
    status_partial: 'Partial Connection',
    status_offline: 'System Offline',
    status_health: 'System Health',
    status_auth: 'Auth',
    status_database: 'Database',
    status_ok: 'Connected',
    status_fail: 'Unavailable',

    // Section titles / shared buttons
    therapy_subtitle: 'Evidence-based exercises to support your mental wellness',
    meditation_subtitle: 'Find your calm with guided sessions and breathing exercises',
    resources_subtitle: 'Music, videos, articles and tools to support your wellbeing',
    appointments_subtitle: 'Book a session with a professional counselor',
    appointments_title: 'Appointments',
    appointment_booked: 'Appointment booked successfully!',
    confirm_booking: 'Confirm Booking',
    insights_title: 'Wellness Insights',
    insights_subtitle: 'Personal analytics and recommendations based on your activity',
    start_exercise: 'Start Exercise',
    learn_more: 'Learn More',
    get_help_now: 'Get Help Now',
    close: 'Close',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    complete: 'Complete',
    add_goal: 'Add Goal',
    book_session: 'Book Session',
    exercise_completed: 'Exercise completed!',
    session_completed: 'Session completed!',
    coming_soon_toast: 'This feature is coming soon',
    footer_about_desc:
      'Confidential mental wellness support designed for university students — mood tracking, therapy tools, meditation and peer support groups, all in one private space.',
    footer_support: 'Support',
    footer_privacy: 'Your Privacy',
    footer_privacy_desc:
      'Your data stays private and confidential. Your mood entries, messages and appointments are never shared without your consent.',
    footer_quick_links: 'Quick Links',
    footer_crisis_title: 'In crisis? You are not alone.',
    footer_crisis_text:
      'Call or text the National Crisis Lifeline at 988 — free, confidential and available 24/7. You matter.',
    footer_contact_support: 'Contact Support',
    footer_student_dashboard: 'Student Dashboard',
    footer_counselor_portal: 'Counselor Portal',
    footer_copyright: '© 2026 Campus Mindspace. All rights reserved.',
    footer_not_medical: 'Not a medical service. For emergencies, call 911.',
  },

  es: {
    // Landing
    welcome_title: 'Campus Mindspace',
    welcome_subtitle: 'Tu santuario personal para el bienestar mental',
    welcome_description:
      'Una plataforma integral de salud mental y bienestar diseñada específicamente para estudiantes universitarios. Encuentra apoyo, recursos y herramientas para navegar los desafíos de la vida académica.',
    enter_title: '¿Listo para comenzar?',
    enter_description:
      'Entra al panel para explorar el seguimiento del estado de ánimo, meditación, herramientas de terapia, juegos y grupos de apoyo.',
    enter_btn: 'Entrar al Panel',
    secure_trusted: 'Seguro y Confiable',
    professional_counselors: 'Consejeros Profesionales',
    privacy_protected: 'Privacidad Protegida',

    // Navigation
    nav_home: 'Inicio',
    nav_therapy: 'Terapia',
    nav_meditation: 'Meditación',
    nav_resources: 'Recursos',
    nav_appointments: 'Citas',
    nav_games: 'Juegos Mentales',
    nav_groups: 'Chat Grupal',
    nav_insights: 'Perspectivas',
    admin_shortcut: 'Admin',
    profile_settings: 'Ajustes',
    profile_help: 'Ayuda y Soporte',
    exit_home: 'Salir al Inicio',

    // Home
    welcome_back: '¡Bienvenido de nuevo, {name}!',
    stat_streak: 'Racha de Días',
    stat_wellness: 'Puntaje de Bienestar',
    stat_sessions: 'Sesiones',
    daily_tip_badge: 'Consejo Diario',
    daily_tip_title: 'Perspectiva de Bienestar',
    new_tip: 'Nuevo Consejo',
    save_tip: 'Guardar',
    tip_saved: 'Consejo guardado en tu colección',
    quick_actions: 'Acciones Rápidas',
    quick_actions_subtitle: 'Accede a tus herramientas y recursos de bienestar',
    therapy_title: 'Recursos de Terapia',
    therapy_description: 'Accede a ejercicios de TCC, TDC y mindfulness',
    meditation_title: 'Meditación',
    meditation_description: 'Sesiones guiadas para aliviar el estrés y concentrarte',
    resources_title: 'Recursos',
    resources_description: 'Música, videos y ayudas de estudio',
    appointment_title: 'Reservar Sesión',
    appointment_description: 'Agenda tiempo con un consejero',
    games_title: 'Juegos Mentales',
    games_description: 'Actividades divertidas para mejorar tu ánimo',
    games_tab_cognitive: 'Juegos Cognitivos',
    games_tab_wellness: 'Actividades de Bienestar',
    games_tab_creativity: 'Herramientas Creativas',
    games_tab_social: 'Juegos Sociales',
    groups_title: 'Chat Grupal',
    groups_description: 'Conéctate con otros que sienten lo mismo',
    complete_pct: '{p}% Completo',
    sessions_count: '3 Sesiones',
    members_count: '5 Miembros',
    popular: 'Popular',
    new_badge: 'Nuevo',
    recent_activity: 'Actividad Reciente',
    live: 'En vivo',
    activity_meditation_title: 'Sesión de Meditación Completada',
    activity_meditation_desc: 'Ejercicio de respiración de 5 minutos • hace 2 minutos',
    activity_mood_title: 'Registro de Ánimo',
    activity_mood_desc: 'Sintiéndome positivo hoy • hace 15 minutos',
    activity_therapy_title: 'Ejercicio de Terapia',
    activity_therapy_desc: 'Hoja de TCC completada • hace 1 hora',
    pts: '+{n} pts',
    your_achievements: 'Tus Logros',
    achievements_subtitle: 'Celebra tus hitos de bienestar',
    badge_streak: 'Maestro de Racha',
    badge_streak_desc: 'Racha de bienestar de 7 días',
    badge_zen: 'Buscador Zen',
    badge_zen_desc: '10 sesiones de meditación',
    badge_champion: 'Campeón de Bienestar',
    badge_champion_desc: 'Completa 30 actividades',
    badge_helper: 'Ayudante Comunitario',
    badge_helper_desc: 'Ayuda a 5 compañeros',
    mood_tracker_title: '¿Cómo te sientes hoy?',
    update_mood: 'Actualizar Ánimo',
    view_history: 'Ver Historial',
    analytics: 'Analítica',
    mood_overwhelmed: 'Sintiéndome abrumado',
    mood_sleep: 'Problemas de sueño',
    mood_social: 'Estrés social',
    mood_happy: '¡Me siento genial!',
    mood_anxious: 'Sintiéndome ansioso',
    mood_lonely: 'Sintiéndome solo',
    mood_updated: '¡Ánimo actualizado exitosamente!',
    coming_soon: 'Próximamente',
    coming_soon_desc:
      'Esta sección se está reconstruyendo en React. Mientras tanto puedes explorarla en el prototipo original en http://127.0.0.1:8000/dashboard.html',

    // Chatbot
    chatbot_title: "¡Hola, soy MindBot!",
    chatbot_subtitle: 'Tu compañero de bienestar mental',
    chatbot_placeholder: 'Escribe tu mensaje...',

    // System status
    status_checking: 'Comprobando sistema...',
    status_cloud: 'Conectado a la Nube',
    status_partial: 'Conexión Parcial',
    status_offline: 'Sistema Sin Conexión',
    status_health: 'Salud del Sistema',
    status_auth: 'Autenticación',
    status_database: 'Base de datos',
    status_ok: 'Conectado',
    status_fail: 'No disponible',

    // Section titles / shared buttons
    therapy_subtitle: 'Ejercicios basados en evidencia para apoyar tu bienestar mental',
    meditation_subtitle: 'Encuentra tu calma con sesiones guiadas y ejercicios de respiración',
    resources_subtitle: 'Música, videos, artículos y herramientas para tu bienestar',
    appointments_subtitle: 'Reserva una sesión con un consejero profesional',
    appointments_title: 'Citas',
    appointment_booked: '¡Cita reservada con éxito!',
    confirm_booking: 'Confirmar Reserva',
    insights_title: 'Perspectivas de Bienestar',
    insights_subtitle: 'Análisis y recomendaciones personalizadas basadas en tu actividad',
    start_exercise: 'Iniciar Ejercicio',
    learn_more: 'Saber Más',
    get_help_now: 'Obtener Ayuda Ahora',
    close: 'Cerrar',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    complete: 'Completar',
    add_goal: 'Añadir Meta',
    book_session: 'Reservar Sesión',
    exercise_completed: '¡Ejercicio completado!',
    session_completed: '¡Sesión completada!',
    coming_soon_toast: 'Esta función estará disponible próximamente',
    footer_about_desc:
      'Apoyo confidencial de bienestar mental diseñado para estudiantes universitarios: seguimiento del estado de ánimo, herramientas terapéuticas, meditación y grupos de apoyo entre pares, todo en un espacio privado.',
    footer_support: 'Soporte',
    footer_privacy: 'Tu Privacidad',
    footer_privacy_desc:
      'Tus datos se mantienen privados y confidenciales. Tus registros de ánimo, mensajes y citas nunca se comparten sin tu consentimiento.',
    footer_quick_links: 'Enlaces Rápidos',
    footer_crisis_title: '¿En crisis? No estás solo.',
    footer_crisis_text:
      'Llama o envía un mensaje a la Línea Nacional de Crisis al 988: gratis, confidencial y disponible 24/7. Tú importas.',
    footer_contact_support: 'Contactar Soporte',
    footer_student_dashboard: 'Panel del Estudiante',
    footer_counselor_portal: 'Portal del Consejero',
    footer_copyright: '© 2026 Campus Mindspace. Todos los derechos reservados.',
    footer_not_medical: 'No es un servicio médico. Para emergencias, llama al 911.',
  },

  fr: {
    // Landing
    welcome_title: 'Campus Mindspace',
    welcome_subtitle: 'Votre sanctuaire personnel pour le bien-être mental',
    welcome_description:
      "Une plateforme complète de santé mentale et de bien-être conçue spécifiquement pour les étudiants universitaires. Trouvez du soutien, des ressources et des outils pour naviguer les défis de la vie académique.",
    enter_title: 'Prêt à commencer ?',
    enter_description:
      "Entrez dans le tableau de bord pour explorer le suivi de l'humeur, la méditation, les outils de thérapie, les jeux et les groupes de soutien.",
    enter_btn: 'Entrer dans le tableau de bord',
    secure_trusted: 'Sécurisé et Fiable',
    professional_counselors: 'Conseillers Professionnels',
    privacy_protected: 'Confidentialité Protégée',

    // Navigation
    nav_home: 'Accueil',
    nav_therapy: 'Thérapie',
    nav_meditation: 'Méditation',
    nav_resources: 'Ressources',
    nav_appointments: 'Rendez-vous',
    nav_games: 'Jeux d’esprit',
    nav_groups: 'Discussion de groupe',
    nav_insights: 'Analyses',
    admin_shortcut: 'Admin',
    profile_settings: 'Paramètres',
    profile_help: 'Aide et support',
    exit_home: "Quitter vers l'accueil",

    // Home
    welcome_back: 'Bon retour, {name} !',
    stat_streak: 'Série de jours',
    stat_wellness: 'Score de bien-être',
    stat_sessions: 'Sessions',
    daily_tip_badge: 'Conseil du jour',
    daily_tip_title: 'Perspective de bien-être',
    new_tip: 'Nouveau conseil',
    save_tip: 'Enregistrer',
    tip_saved: 'Conseil enregistré dans votre collection',
    quick_actions: 'Actions rapides',
    quick_actions_subtitle: 'Accédez à vos outils et ressources de bien-être',
    therapy_title: 'Ressources de thérapie',
    therapy_description: 'Accédez à des exercices de TCC, TCD et pleine conscience',
    meditation_title: 'Méditation',
    meditation_description: 'Sessions guidées pour le stress et la concentration',
    resources_title: 'Ressources',
    resources_description: 'Musique, vidéos et aides à l’étude',
    appointment_title: 'Réserver une session',
    appointment_description: 'Planifiez un rendez-vous avec un conseiller',
    games_title: 'Jeux d’esprit',
    games_description: 'Activités amusantes pour améliorer votre humeur',
    games_tab_cognitive: 'Jeux Cognitifs',
    games_tab_wellness: 'Activités de Bien-Être',
    games_tab_creativity: 'Outils Créatifs',
    games_tab_social: 'Jeux Sociaux',
    groups_title: 'Discussion de groupe',
    groups_description: 'Connectez-vous avec d’autres qui ressentent la même chose',
    complete_pct: '{p}% Complet',
    sessions_count: '3 Sessions',
    members_count: '5 Membres',
    popular: 'Populaire',
    new_badge: 'Nouveau',
    recent_activity: 'Activité récente',
    live: 'En direct',
    activity_meditation_title: 'Session de méditation terminée',
    activity_meditation_desc: 'Exercice de respiration de 5 min • il y a 2 minutes',
    activity_mood_title: 'Enregistrement d’humeur',
    activity_mood_desc: 'Je me sens positif aujourd’hui • il y a 15 minutes',
    activity_therapy_title: 'Exercice de thérapie',
    activity_therapy_desc: 'Feuille de TCC terminée • il y a 1 heure',
    pts: '+{n} pts',
    your_achievements: 'Vos réalisations',
    achievements_subtitle: 'Célébrez vos jalons de bien-être',
    badge_streak: 'Maître de la série',
    badge_streak_desc: 'Série de bien-être de 7 jours',
    badge_zen: 'Chercheur de zen',
    badge_zen_desc: '10 sessions de méditation',
    badge_champion: 'Champion du bien-être',
    badge_champion_desc: 'Terminez 30 activités',
    badge_helper: 'Aide communautaire',
    badge_helper_desc: 'Aidez 5 pairs',
    mood_tracker_title: 'Comment vous sentez-vous aujourd’hui ?',
    update_mood: 'Mettre à jour l’humeur',
    view_history: "Voir l'historique",
    analytics: 'Analytique',
    mood_overwhelmed: 'Me sentir dépassé',
    mood_sleep: 'Problèmes de sommeil',
    mood_social: 'Stress social',
    mood_happy: 'Je me sens bien !',
    mood_anxious: 'Me sentir anxieux',
    mood_lonely: 'Me sentir seul',
    mood_updated: 'Humeur mise à jour avec succès !',
    coming_soon: 'Bientôt disponible',
    coming_soon_desc:
      "Cette section est en cours de reconstruction en React. En attendant, vous pouvez l'explorer dans le prototype original à http://127.0.0.1:8000/dashboard.html",

    // Chatbot
    chatbot_title: "Bonjour, je suis MindBot !",
    chatbot_subtitle: 'Votre compagnon de bien-être mental',
    chatbot_placeholder: 'Écrivez votre message...',

    // System status
    status_checking: 'Vérification du système...',
    status_cloud: 'Connecté au cloud',
    status_partial: 'Connexion partielle',
    status_offline: 'Système hors ligne',
    status_health: 'Santé du système',
    status_auth: 'Auth',
    status_database: 'Base de données',
    status_ok: 'Connecté',
    status_fail: 'Indisponible',

    // Section titles / shared buttons
    therapy_subtitle: "Exercices fondés sur des preuves pour soutenir votre bien-être mental",
    meditation_subtitle: "Trouvez votre calme avec des sessions guidées et des exercices de respiration",
    resources_subtitle: "Musique, vidéos, articles et outils pour votre bien-être",
    appointments_subtitle: "Réservez une session avec un conseiller professionnel",
    appointments_title: 'Rendez-vous',
    appointment_booked: 'Rendez-vous réservé avec succès !',
    confirm_booking: 'Confirmer la Réservation',
    insights_title: 'Analyses de bien-être',
    insights_subtitle: "Analyses et recommandations personnalisées basées sur votre activité",
    start_exercise: "Commencer l'exercice",
    learn_more: 'En savoir plus',
    get_help_now: "Obtenir de l'aide",
    close: 'Fermer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    complete: 'Terminer',
    add_goal: 'Ajouter un objectif',
    book_session: 'Réserver une session',
    exercise_completed: 'Exercice terminé !',
    session_completed: 'Session terminée !',
    coming_soon_toast: 'Cette fonctionnalité arrive bientôt',
    footer_about_desc:
      "Un soutien confidentiel de bien-être mental conçu pour les étudiants universitaires : suivi de l'humeur, outils thérapeutiques, méditation et groupes de soutien entre pairs, le tout dans un espace privé.",
    footer_support: 'Support',
    footer_privacy: 'Votre Vie Privée',
    footer_privacy_desc:
      'Vos données restent privées et confidentielles. Vos humeurs, messages et rendez-vous ne sont jamais partagés sans votre consentement.',
    footer_quick_links: 'Liens Rapides',
    footer_crisis_title: 'En crise ? Vous n\'êtes pas seul.',
    footer_crisis_text:
      'Appelez ou envoyez un SMS à la ligne nationale de crise au 988 — gratuit, confidentiel et disponible 24h/24. Vous comptez.',
    footer_contact_support: 'Contacter le Support',
    footer_student_dashboard: 'Tableau de bord étudiant',
    footer_counselor_portal: 'Portail du Conseiller',
    footer_copyright: '© 2026 Campus Mindspace. Tous droits réservés.',
    footer_not_medical: "Ce n'est pas un service médical. En cas d'urgence, appelez le 911.",
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('campusMindspace_language') || 'en')

  useEffect(() => {
    localStorage.setItem('campusMindspace_language', lang)
    document.documentElement.lang = lang
  }, [lang])

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}
